development:
  <<: *default
  database: sinatra_seq_dev
  password: 123

test:
  <<: *default
  database: sinatra_seq_test
  password: 123

production:
  <<: *default
  database: sinatra_seq_prod
  password: 123

default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: sinatra_admin
  timeout: 5000
  reaping_frequency: 30
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
