ENV['DATABASE'] = 'sinatra_seq_dev' if ENV['RACK_ENV'] == 'development'
ENV['DATABASE'] = 'sinatra_seq_test' if ENV['RACK_ENV'] == 'test'
ENV['DATABASE'] = 'sinatra_seq_prod' if ENV['RACK_ENV'] == 'production'
